[package]
name = "nivalis"
description = "A typestate-driven, pure-Rust implementation of the Noise Protocol Framework"
homepage = "https://github.com/mathieuemery/nivalis"
documentation = "https://docs.rs/nivalis/"
repository = "https://github.com/mathieuemery/nivalis"
authors = ["Mathieu Emery <mathieuemery@proton.me>"]
license = "MIT"
categories = ["cryptography", "no-std"]
readme = "README.md"
keywords = ["noise", "protocol", "crypto", "handshake"]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
aes-gcm = { version = "0.11.0", default-features = false, features = ["aes", "alloc"] }
blake2 = { version = "0.11.0-rc.6", default-features = false }
chacha20poly1305 = { version = "0.11.0", default-features = false, features = ["alloc"] }
cx448 = { version = "0.1.1", default-features = false }
hmac = { version = "0.13", default-features = false }
rand_core = { version = "0.10.1", default-features = false }
sha2 = { version = "0.11", default-features = false }
tracing = { version = "0.1.44", default-features = false }
x25519-dalek = { version = "3.0.0", default-features = false, features = ["static_secrets"] }

[dev-dependencies]
hex = "0.4.3"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[[example]]
name = "xx"
path = "examples/xx.rs"

[[example]]
name = "ikpsk2"
path = "examples/ikpsk2.rs"
