[package]
name = "nivalis"
description = "A typestate-driven, pure-Rust implementation of the Noise Protocol Framework"
homepage = "https://github.com/mathieuemery/nivalis"
documentation = "https://docs.rs/nivalis/"
repository = "https://github.com/mathieuemery/nivalis"
authors = ["Mathieu Emery <mathieuemery@proton.me>"]
license = "MIT"
categories = ["cryptography"]
readme = "README.md"
keywords = ["noise", "protocol", "crypto", "handshake"]
version = "0.1.1"
edition = "2024"
rust-version = "1.85"

[dependencies]
aes-gcm = "0.11.0"
anyhow = "1.0.103"
blake2 = "0.11.0-rc.6"
chacha20poly1305 = "0.11.0"
cx448 = "0.1.1"
getrandom = "0.4.3"
hmac = "0.13"
sha2 = "0.11"
tracing = "0.1.44"
x25519-dalek = { version = "3.0.0", features = ["getrandom", "static_secrets"] }

[dev-dependencies]
hex = "0.4.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[[example]]
name = "xx"
path = "examples/xx.rs"

[[example]]
name = "ikpsk2"
path = "examples/ikpsk2.rs"