//! Constants used by the lib

/// The maximum length of a message as defined
/// in the protocol.
pub const MAX_MESSAGE_LEN: usize = 65535;

/// The key length length used by all encryption
/// algorithms.
pub const ENCRYPTION_KEY_LEN: usize = 32;

/// The length in bytes of the nonce passed
/// to the AEAD cipher (96 bits)
pub const NONCE_LEN: usize = 12;

/// The length of the tag generated by the 
/// AEAD cipher (128 bits)
pub const TAG_LEN: usize = 16;
