name: Validation CI
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  lint-and-test:
    name: clippy + tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-features

  # Inspired from https://github.com/RustCrypto/AEADs/blob/master/.github/workflows/aes-gcm.yml
  no_std_build:
    name: no_std build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - thumbv7em-none-eabi
          - riscv32imac-unknown-none-elf
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --target ${{ matrix.target }}
